services:
  - type: web
    name: big-api-task
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn index:app --bind 0.0.0.0:$PORT"
    autoDeploy: true